authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

basketapp/urls.py
from django.conf.urls import url
from django.urls import path
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [

    url(r'^$', basketapp.basket, name='view'),

    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    url(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit,
        name='edit'),
    url(r'^create/$', basketapp.OrderCreate, name='order_create')
]



# path('add/<int:pk>/', basketapp.basket_add, name='add'),

myproject/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import adminapp as adminapp
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', mainapp.products, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += staticfiles_urlpatterns()

basketapp/models.py
from django.db import models
from mainapp.models import Product
from django.conf import settings
from django.db.models import CASCADE

# Create your models here.


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)
    add_datetime = models.DateTimeField(verbose_name='время добавления',
                                        auto_now_add=True)
#    close_datetime = models.DateTimeField(verbose_name='время закрытия',
#                                        auto_now_add=False)
#    first_name =
#    last_name =
#    email
#    address
#    postal_code
#    city


    def get_product_cost(self):
        return self.product.price * self.quantity

    def get_totalquantity(self):
        items = Basket.objects.filter(user=self.user)
        totalquantity = sum(item.quantity for item in items)
        return totalquantity

    def get_totalcost(self):
        items = Basket.objects.filter(user=self.user)
        totalquantity = sum(item.product.price*item.quantity for item in items)
        return totalquantity


class Order(models.Model):
    first_name = models.CharField(verbose_name='Имя', max_length=50)
    last_name = models.CharField(verbose_name='Фамилия', max_length=50)
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(verbose_name='Адрес', max_length=250)
    postal_code = models.CharField(verbose_name='Почтовый код', max_length=20)
    city = models.CharField(verbose_name='Город', max_length=100)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)
    closed = models.DateTimeField(verbose_name='Закрыт', auto_now_add=True )
    canseled = models.DateTimeField(verbose_name='Отменён', auto_now_add=True)

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Цена',
                                max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(verbose_name='Количество',
                                           default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, default=None)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

basketapp/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = '__all__'
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

basketapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse, Http404
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from basketapp.models import Basket
from mainapp.models import Product
from .forms import OrderCreateForm
from .models import OrderItem
# Create your views here.


@login_required
def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product')
    context = {'title': title, 'basket_items': basket_items}

    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):

    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)
    old_basket_item = Basket.objects.filter(user=request.user, product=product)

    if old_basket_item:
        old_basket_item[0].quantity += 1
        old_basket_item[0].save()
    else:
        new_basket_item = Basket(user=request.user, product=product)
        new_basket_item.quantity += 1
        new_basket_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    if request.method == 'POST':
        basket_record = get_object_or_404(Basket, pk=pk)
        basket_record.delete()
    else:
        raise Http404

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product')

        context = {
            'basket_items': basket_items,
        }

        result = render_to_string('basketapp/includes/inc_basket_list.html', context)

        return JsonResponse({'result': result})


@login_required
def OrderCreate(request):
    cart = Basket.objects.filter(user=request.user)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item.product,
                                         price=item.product.price,
                                         quantity=item.quantity,
                                         user=request.user)
            # cart.clear()
            return render(request,
                          'basketapp/order_created.html',
                          {'order': order})

    form = OrderCreateForm()
    return render(request,
                  'basketapp/order_create.html',
                  {'cart': cart, 'form': form})

basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title}}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="basket_container">        
        <div class="h2 text-center head">
            Ваша корзина, 
            {% if user.first_name %}
                {{ user.first_name|title}}
            {% else %}Пользователь
            {% endif %}
        </div>
        
        
        {% block content %}

        {% endblock %}
        
	</div>
</body>
</html>

basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="basket_list">
    {% include 'basketapp/includes/inc_basket_list.html' %}
</div>


<button class="btn btn-success pull-left">
    <a href="{% url 'basket:order_create' %}" class="btn">Оформить заказ</a>
</button>


<button class="btn">
    <a href="{% url 'index' %}" class="btn">Вернуться</a>
</button>


{% endblock %}

basketapp/templates/basketapp/order_create.html
{% extends 'basketapp/base.html' %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block content %}
  <h1>Оформление заказа</h1>
  <div class="col-sm-4">
    <h2>Заполните форму</h2>
    <form class="order-form" action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправить">
    </form>
  </div>

  <div class="order-info col-sm-8">
    <h2>Ваш заказ</h2>

<table class="table table-striped">
     <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Цена</th>
      </tr>
      {% for item in cart  %}


    <tr>
        <td><img src="/media/{{ item.product.image|default:'products_images/default.png' }}"
        alt="{{ item.product.name }}" ></td>
        <td>{{item.product.name}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.product.price}}руб</td>

    </tr>


      {% endfor %}

      <td></td><td><strong>Всего:</strong></td><td><strong>{{ cart.0.get_totalquantity }} шт.</strong> </td>
      <td><strong>{{ cart.0.get_totalcost }} руб</strong></td>


</table>


     <button class="btn btn-info">
            <a href="{% url 'index' %}">
                Продолжить покупки
            </a>
    </button>
  </div>
{% endblock %}

basketapp/templates/basketapp/order_created.html
{% extends 'basketapp/base.html' %}


{% block title %}
  Спасибо за заказ
{% endblock %}

{% block content %}
  <h1>Спасибо за заказ</h1>
  <p>Идентификатор вашего заказа: {{ order.id }}</p>

<button class="btn btn-info">
            <a href="{% url 'index' %}">
                Вернуться в магазин
            </a>
</button>
{% endblock %}