adminapp/urls.py
from django.conf.urls import url
import adminapp.views as adminapp
from django.urls import path

app_name = 'admin'

urlpatterns = [
    url(r'^users/create/$', adminapp.user_create, name='user_create'),
    url(r'^users/read/$', adminapp.UserListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update,
        name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete,
        name='user_delete'),
    # path('users/update/password/<int:pk>/', adminapp.password_change,
    #     name='user_update'),

    url(r'^categories/create/$', adminapp.CategoryCreateView.as_view(),
        name='category_create'),
    # url(r'^categories/read/$', adminapp.CategoryListView.as_view(),
    #     name='categories'),
    url(r'^categories/read/$', adminapp.categories, name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$',
        adminapp.CategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$',
        adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    url(r'^products/create/category/(?P<pk>\d+)/$',
        adminapp.product_create, name='product_create'),
    # url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products,
    #     name='products'),
    path('products/read/<int:pk>/', adminapp.products, name='products'),
    # url(r'^products/read/(?P<pk>\d+)/$', adminapp.products,
    #     name='product_read'),
    url(r'^products/detail/(?P<pk>\d+)/$',
        adminapp.ProductDetailView.as_view(), name='products_detail_view'),
    url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update,
        name='product_update'),
    url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete,
        name='product_delete'),

    path('contacts/read/', adminapp.ContactsListlView.as_view(),
         name='contacts'),
    url(r'^contacts/create/$', adminapp.ContactCreateView.as_view(),
        name='contact_create'),
    url(r'^contacts/update/(?P<pk>\d+)/$',
        adminapp.ContactUpdateView.as_view(), name='contact_update'),
    url(r'^contacts/delete/(?P<pk>\d+)/$',
        adminapp.ContactDeleteView.as_view(), name='contact_delete'),

    url(r'^orders/read/', adminapp.orders, name='orders'),

]

# urlpatterns += patterns('django.contrib.auth.views',
#   url(r'^user/(?P<user_id>\d+)/user_edit/password/$', 'password_change')
# )

authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import adminapp as adminapp
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', mainapp.products, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += staticfiles_urlpatterns()

adminapp/models.py
# from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory
from mainapp.models import Product
from contactsapp.models import Contacts


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()



class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductCategoryForm(forms.ModelForm):
    name = forms.CharField(help_text='Введите название',
                           label='Название',
                           widget=forms.Textarea(attrs={
                               'placeholder': 'Название'
                           }))

    class Meta:
        model = ProductCategory
        fields = '__all__'


class ContactsEditForm(forms.ModelForm):
    class Meta:
        model = Contacts
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactsEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.contrib.auth.decorators import user_passes_test
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ContactsEditForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from adminapp.forms import ProductCategoryEditForm
from adminapp.forms import ProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.base import ContextMixin
from contactsapp.models import Contacts
from basketapp.models import Basket, Order, OrderItem
from django.contrib import admin
# Create your views here.


@user_passes_test(lambda u: u.is_superuser)
def orders(request):
    title = 'админка/заказы'

    categories_list = Basket.objects.all()

    context = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/orders.html', context)

def OrderCreate(request):
    cart = Basket(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request, 'orders/order/created.html', {'order': order})

    form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form})

class CaptionMixin(ContextMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = 'Мой заголовок страницы'
        return context


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UserListView, self).dispatch(*args, **kwargs)


class ContactsListlView(ListView):
    model = Contacts
    template_name = 'adminapp/contacts.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ContactsListlView, self).dispatch(*args, **kwargs)


class ContactCreateView(CreateView, CaptionMixin):
    model = Contacts
    template_name = 'adminapp/contact_update.html'
    success_url = reverse_lazy('admin:contacts')
    fields = '__all__'


class ContactUpdateView(UpdateView):
    model = Contacts
    template_name = 'adminapp/contact_update.html'
    success_url = reverse_lazy('admin:contacts')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(ContactUpdateView,
                        self).get_context_data(**kwargs)
        context['title'] = 'адреса/редактирование'

        return context


class ContactDeleteView(DeleteView):
    model = Contacts
    template_name = 'adminapp/contact_delete.html'
    success_url = reverse_lazy('admin:contacts')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class CategoryListView(ListView, CaptionMixin):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    # paginate_by = 20
    # context_object_name = 'categories'
    #
    # def get_queryset(self):
    #     categories_list = ProductCategory.objects.filter(name__contains='о')
    #     return categories_list


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CategoryUpdateView,
                        self).get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'

        return context


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'
    success_url = reverse_lazy('admin:products')
    fields = '__all__'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView,
                        self).get_context_data(**kwargs)
        context['title'] = 'продукты/редактирование'

        return context


class ProductCreateView(CreateView, CaptionMixin):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin:products')
    fields = '__all__'


@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'админка/пользователи'
    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser',
                                                 '-is_staff', 'username')

    context = {
        'title': title,
        'objects': users_list
    }

    return render(request, 'adminapp/users.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()

    context = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES,
                                          instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update',
                                                args=[pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    context = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'
    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    context = {
        'title': title,
        'user_to_delete': user
    }

    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/categories.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'категории/создание'

    if request.method == 'POST':
        category_form = ProductCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin:categories'))
    else:
        category_form = ProductCategoryEditForm()

    context = {'title': title, 'update_form': category_form}

    return render(request, 'adminapp/category_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'категории/редактирование'

    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        edit_form = ProductCategoryEditForm(request.POST, request.FILES,
                                            instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update',
                                                args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)

    context = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/category_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'категории/удаление'

    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    context = {'title': title, 'category_to_delete': category}

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="categories_list">
		<button class="new_category">
			<a href="{% url 'admin:category_create' %}">новая категория</a>
		</button>
		
		{% for object in objects %}
			<div class="category_record
            {% if not object.is_active %} not_active {% endif %}">
			
				<div class="category_name">
					{{ object.name|title }}
				</div>
				<div class="category_actions">
					<button>
						<a href="{% url 'admin:products' object.pk %}">товары категории</a>
					</button>
					<button>
						<a href="{% url 'admin:category_update' object.pk %}">редактировать</a>
					</button>
					<button>
						<a href="{% url 'admin:category_delete' object.pk %}">удалить</a>
					</button>
				</div>
				<div class="category_desc">
					{{ object.description|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить категорию <strong>{{ category_to_delete.name }}</strong>?
        <form action="{% url 'admin:category_delete' category_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:categories' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/contact_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ contacts.name }} ?
        <form action="{% url 'admin:contact_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:contacts' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/contact_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}
{% block content %}
<form class ="form-horizontal" method ="post" enctype ="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
        <input class ="form-control" type="submit" value="сохранить">
</form>

<button class="btn btn-round form-control last">
    <a href ="{% url 'admin:contacts' %}">к списку адресов</a>
</button>
{% endblock %}

adminapp/templates/adminapp/contacts.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="products_list">
		<button class="new_product">
		<a href="{% url 'admin:contact_create'%}">новый адрес</a>
		</button>

		{% for object in object_list %}
			<div class="product_record {% if not object.is_active %}not_active{% endif %}">
				<img src="/media/{{ object.image|default:'contact_avatars/default.jpg' }}" alt="{{ object.name }}">
				<div class="product_actions">
					Офис
					<button>
						<a href="{% url 'admin:contact_update' object.pk %}">
						редактировать
						</a>
					</button>
					<button>
						<a href="{% url 'admin:contact_delete' object.pk %}">
						удалить
						</a>
					</button>
				</div>
				<div class="product_name">

						<strong>{{ object.name }}</strong>

					
				</div>
				<div class="summary">
					Населенный пункт:<br>
					{{ object.city }} 
				</div>
				<div class="summary">
					email:<br>
					{{ object.email }}
				</div>
				<div class="summary">
					phone:<br>
					{{ object.phone }}
				</div>
				<div class="product_desc">
					 адрес:<br>
					{{ object.address }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

adminapp/templates/adminapp/contacts_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class = "product_read ">
        <div class="product_name">
            Адрес <strong>
            {{ object.name|title}}</strong>
        </div>

        
        <div class="summary">
            <b>город</b>
            <p>{{ object.cyti }}</p>
            <b>Телефон</b>
            <p>{{ object.phone }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %} да {% else %} нет {% endif%}</p>
            
        </div>
        <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.address }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.email }}</p>
        </div>


    </div>
{% endblock %}
            
    

adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="products_list">


		{% for object in objects %}
			<div class="product_record">
<!--				<img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">-->
				<div class="product_record">
					{{ object.user|title }}
                </div>

                <div class="summary">
					{{ object.product }}
                </div>
                <div class="summary">
					{{ object.quantity }}
                </div>
                <span class="product_price">{{ object.product.price }}руб</span>




			</div>
		{% endfor%}
	</div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите удалить продукт <strong>{{ product_to_delete.name }}</strong>?
        <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' product_to_delete.category.pk %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class = "product_read ">
        <div class="product_name">
            Продукт<strong>{{object.category.name|title}}
            {{ object.name|title}}</strong>
        </div>
<div class="user_avatar">
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
        alt="{{ object.name }}">
</div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %} да {% else %} нет {% endif%}</p>
            <p>
                <button>
                    <a href ="{% url 'admin:product_update' object.pk %}">
                    редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:product_delete' object.pk %}">
                    удалить</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:products' object.category.pk %}">
                    назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.desc }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.desc_full }}</p>
        </div>
    </div>
{% endblock %}
            
    

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">

        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>

        

        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку продуктов
            </a>
        </button>


{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="products_list">
		<button class="new_product">
			<a href="{% url 'admin:product_create' category.pk %}">новый продукт</a>
		</button>
		
		{% for object in objects %}
			<div class="product_record">
				<img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
				<div class="product_name">
					{{ object.name|title }}
				</div>
				<div class="product_actions">
					<button>
						<a href="{% url 'admin:products_detail_view' object.pk %}">подробнее</a>
					</button>
					<button>
						<a href="{% url 'admin:product_update' object.pk %}">редактировать</a>
					</button>
					<button>
						<a href="{% url 'admin:product_delete' object.pk %}">удалить</a>
					</button>
				</div>
				<div class="summary">
					<b>цена</b>
					<p>{{ object.price }} руб</p>
					<b>количество</b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="product_desc">
					{{ object.desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ user_to_delete.username }} {% if user_to_delete.first_name %}
                    ({{ user_to_delete.first_name|title }}
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}?
        <form action="{% url 'admin:user_delete' user_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:users' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="users_list">
		<button class="new_user">
			<a href={% url 'admin:user_create' %}>
			новый пользователь
			</a>
		</button>

		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
					<button>
						<a href={% url 'admin:user_update' object.pk %}>
						редактировать
						</a>
					</button>
					<button>
						<a href={% url 'admin:user_delete' object.pk %}>
						удалить
						</a>
					</button>
				</div>
				<div class="user_name">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					
					{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% if object.last_name %}
							<p>{{ object.last_name|title }}</p>
						{% endif %}
					{% endif %}
					
				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}