adminapp/urls.py
from django.conf.urls import url
import adminapp.views as adminapp
from django.urls import path

app_name = 'admin'

urlpatterns = [
    url(r'^users/create/$', adminapp.user_create, name='user_create'),
    url(r'^users/read/$', adminapp.UserListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update,
        name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete,
        name='user_delete'),
    # path('users/update/password/<int:pk>/', adminapp.password_change,
    #     name='user_update'),

    url(r'^categories/create/$', adminapp.CategoryCreateView.as_view(),
        name='category_create'),
    # url(r'^categories/read/$', adminapp.CategoryListView.as_view(),
    #     name='categories'),
    url(r'^categories/read/$', adminapp.categories, name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$',
        adminapp.CategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$',
        adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    url(r'^products/create/category/(?P<pk>\d+)/$',
        adminapp.product_create, name='product_create'),
    # url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products,
    #     name='products'),
    path('products/read/<int:pk>/', adminapp.products, name='products'),
    # url(r'^products/read/(?P<pk>\d+)/$', adminapp.products,
    #     name='product_read'),
    url(r'^products/detail/(?P<pk>\d+)/$',
        adminapp.ProductDetailView.as_view(), name='products_detail_view'),
    url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update,
        name='product_update'),
    url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete,
        name='product_delete'),

    path('contacts/read/', adminapp.ContactsListlView.as_view(),
         name='contacts'),
    url(r'^contacts/create/$', adminapp.ContactCreateView.as_view(),
        name='contact_create'),
    url(r'^contacts/update/(?P<pk>\d+)/$',
        adminapp.ContactUpdateView.as_view(), name='contact_update'),
    url(r'^contacts/delete/(?P<pk>\d+)/$',
        adminapp.ContactDeleteView.as_view(), name='contact_delete'),

    url(r'^orders/read/', adminapp.orders, name='orders'),

]

# urlpatterns += patterns('django.contrib.auth.views',
#   url(r'^user/(?P<user_id>\d+)/user_edit/password/$', 'password_change')
# )

authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

basketapp/urls.py
from django.conf.urls import url
from django.urls import path
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [

    url(r'^$', basketapp.basket, name='view'),

    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    url(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit,
        name='edit'),
    url(r'^create/$', basketapp.OrderCreate, name='order_create')
]



# path('add/<int:pk>/', basketapp.basket_add, name='add'),

contactsapp/urls.py
#from django.urls import path
from django.conf.urls import url
import contactsapp.views as contactsapp

app_name = 'contacts'

urlpatterns = [url(r'^$', contactsapp.contact, name='contact')]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'mainapp'

urlpatterns = [
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    url(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products,
        name='page')
]
urlpatterns += staticfiles_urlpatterns()

myproject/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import adminapp as adminapp
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', mainapp.products, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += staticfiles_urlpatterns()

mainapp/models.py
from django.db import models
from django.db.models import CASCADE


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


#  методичка 3
class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    desc = models.CharField(verbose_name='краткое описание', max_length=32,
                            blank=True)
    desc_full = models.TextField(verbose_name='полное описание', db_index=True,
                                 blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0,
                                verbose_name='цена')
    quantity = models.PositiveIntegerField(verbose_name='остаток на складе',
                                           null=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
# import logging
# from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import dateformat
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.conf import settings
from basketapp.models import Basket

# logging.basicConfig(filename="mainapp_views.log", level=logging.DEBUG,
#                   format="%(levelname)-10s %(asctime)s %(message)s")


# Create your views here.

# def main(request):
#     title = 'главная'
#     category = ProductCategory.objects.all()
#     # logging.debug("категории", category)
#     products = Product.objects.all()[:4]
#
#     content = {'title': title, 'products': products, 'category': category, }
#     return render(request, 'mainapp/base.html', content)


def getBasket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def products(request, pk=None, page=1):
    title = 'welcome to woodhouse'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = []

    now = dateformat.format(datetime.now(), settings.DATE_FORMAT)

    if request.user.is_authenticated:
        basket = getBasket(request.user)

    if pk:
        if pk == '0':
            category = {'pk': 0,
                        'name': 'все продукты'}
            products = Product.objects.filter(category__pk=pk,
                category__is_active=True).order_by('-price')

        # is_active=True
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(is_active=True, category__pk=pk,
                                    category__is_active=True).order_by('price')

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {'welcome': title, 'links_menu': links_menu,
                   'category': category, 'products': products_paginator,
                   'now': now, 'basket': basket, }

        return render(request, 'mainapp/products_list.html', context)

    products = Product.objects.filter(is_active=True, category__is_active=True)

    context = {'welcome': title, 'now': now, 'products': products,
               'links_menu': links_menu, 'category': {'name': 'все продукты'},
               'pk': 0, 'basket': basket, 'Контакты': 'contact'}

    return render(request, 'mainapp/products_list.html', context)


def product(request, pk):
    title = 'продукты'
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': getBasket(request.user),
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<title>
		{%block title%} {%endblock%}
	</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="{% static 'js/scripts.js' %}">
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js">

	  </script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js">

	  </script>
    <![endif]-->
	<link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">
</head>

<body>


   <div id="hut"></div>


	<div id="wrapper">

		<div id="header">
			<div id="headerInside">

				<a href="{% url 'index' %}"><img src="{% static 'img/sunrise_logo.png' %}" alt="Годовые кольца"></a>

				<div id="quadratik">
					{% if category.id > 0 %}
					<h1>{{category.name|upper}}</h1>
					{% else%}
					<h1>{{welcome|upper}}</h1>
					{% endif%}

					<p>Сегодня {{now}}</p>
                    <p>пилим, строгаем, продаём недорого</p>



				</div>

			</div>

			<div id="social">
				<ul>
					<li>
						<div id="facebook"> <a href="http://www.facebook.com"><i class="fa fa-facebook" style="color: white"></i></a></div>
						<!--пейсбух-->
					</li>
					<li>
						<div id="twitter"> <a href="http://www.twitter.com"><i class="fa fa-twitter" style="color: white" ></i></a></div>
						<!--свитер-->
					</li>
					<li>
						<div id="you-tube"> <a href="http://www.you-tube.com"><i class="fa fa-youtube" style="color: white" ></i></a></div>
						<!--тытруба-->
					</li>
					<li>
						<div id="pinterest"> <a href="http://www.pinterest.com"><i class="fa fa-pinterest" style="color: white"></i></a></div>
						<!--пинтерест-->
					</li>
					<li>
						<div id="instagram"> <a href="http://www.instagram.com"><i class="fa fa-instagram" style="color: white"></i></a></div>
						<!--ин сто грамм-->
					</li>
				</ul>
			</div>

			<div id="batten">
				<h1>Batten gut 20!8</h1>
				<p>Супер лёгкая половая доска из сосны и березовой коры<br> непревзойдённые точность и комфорт</p>
			</div>

			<div id="knopka"><a href="/basket/">В КОРЗИНУ</a>

			</div>



		</div>

        <div id="content">
        {% include "mainapp/inc-menu.html" %}

		{% block content%} {%endblock%}
        </div>





        <div id="footer">
			<div id="brands">
				<div class="brand"><img src="{% static 'img/image001.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image002.png'%} " width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image003.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image004.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image005.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image006.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image007.png' %}" width="134" height="134" alt="#"> </div>
				<div class="brand"><img src="{% static 'img/image008.png' %}" width="134" height="134" alt="#"> </div>
			</div>

			<div id="sto_gramm"> <h3 class="text-center">Мы в Instagramm</h3>
				<div id="sto_photo">

					<div class="photo">
						<img src="{% static 'img/001.jpg'%}" width="165" height="165" alt="#">
					</div>
					<div class="photo">
						<img src="{% static 'img/002.jpg' %}" width="165" height="165" alt="#">
					</div>
					<div class="photo">
						<img src="{% static 'img/003.jpg' %}" width="165" height="165" alt="#">
					</div>
					<div class="photo">
						<img src="{% static 'img/004.jpg' %}" width="165" height="165" alt="#">
					</div>
					<div class="photo">
						<img src="{% static 'img/005.jpg' %}" width="165" height="165" alt="#">
					</div>
					<div class="photo">
						<img src="{% static 'img/006.jpg' %}" width="165" height="165" alt="#">
					</div>
				</div>
			</div>
			<div id="social_bottom">
				<div id="face">
					<a href="https://www.facebook.com/">
									<i class="fa fa-facebook fa-5x"></i>
								</a>
				</div>
				<div id="twi">
					<a href="https://twitter.com/">
									<i class="fa fa-twitter fa-5x"></i>
								</a>
				</div>
				<div id="pin">
					<a href="https://ru.pinterest.com/">
									<i class="fa fa-pinterest fa-5x"></i>
								</a>
				</div>
			</div>
		</div>





    </div>
    <div id=footer_text>

				<div id="category">
					<h1>Категории</h1>
					<ul>
						<li>
							<a href="#">
								<p>Главная</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>О нас</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Каталог товаров</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Будущее</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Новые поступления</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Наши Блохи</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Контакты</p>
							</a>
						</li>
					</ul>
				</div>

				<div id="account">
					<h1>Аккаунт</h1>
					<ul>
						<li>
							<a href="#">
								<p>Ваш аккаунт</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>О вас</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Адреса</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Акции</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>История заказов</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Ваши адреса</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Поисковые запросы</p>
							</a>
						</li>
					</ul>
				</div>

				<div id="support">
					<h1>Помощь</h1>
					<ul>
						<li>
							<a href="#">
								<p>Карта сайта</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Поисковые запросы</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Расширенный поиск</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Мобила</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Напишите нам</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Вакансии</p>
							</a>
						</li>
						<li>
							<a href="#">
								<p>Адреса лесоповалов</p>
							</a>
						</li>
					</ul>
				</div>

				<div id="newsletter">
					<h1>Новости</h1>
					<br>
					<p id="news"><label for="email">Подпишитесь на наши новости! Введите свой e-mail</label></p>
					<div id="subscribe">
						<label><input type="text" name="addr" id="email" maxlength="35" placeholder="ВВЕДИТЕ АДРЕС">
						<a id="submit" href="#">SUBMIT</a>
						</label>
					</div>

					<div id="cards">
						<img class="card" src="{% static 'img/maestero.png' %}" alt="маэстро">
						<img class="card" src="{% static 'img/mastercard.png' %}" alt="мастер">
						<img class="card" src="{% static 'img/aex.png' %}" alt="аех">
						<img class="card" src="{% static 'img/paypal.png' %}" alt="пайпал">
						<img class="card" src="{% static 'img/discover.png' %}" alt="дисковер">
						<img class="card" src="{% static 'img/visa_straight.png' %}" alt="виза">
					</div>
				</div>

				<div id="about_us">
					<h1>О нас</h1>
					<h2>Мы к вам приехали на час. Привет! Бонжур! Хелло! А ну, скорей любите нас. Вам крупно повезло!</h2>
					<h3>Телефон:</h3>
					<div id="allo">322-233-332-322</div>

					<h3>e-mail:</h3>
					<div id="pismo"><a href="#">yolki@palky.ru</a></div>
				</div>

			</div>

	<div id="footer_down_wrapper">
            <div id="footer_down">
				<p>© YolkiPalkY</p>
				<div id="social_footer">
					<a href="https://www.facebook.com/">
						<i class="fa fa-facebook" aria-hidden="true"></i>
					</a>
					<a href="https://www.twitter.com/">
						<i class="fa fa-twitter" aria-hidden="true"></i>
					</a>
					<a href="https://www.pinterest.com/">
						<i class="fa fa-pinterest-p" aria-hidden="true"></i>
					</a>
					<a href="https://plus.google.com/discover">
						<i class="fa fa-google-plus" aria-hidden="true"></i>
					</a>
					<a href="https://www.tumblr.com/">
						<i class="fa fa-tumblr" aria-hidden="true"></i>
					</a>
					<a href="https://www.instagram.com/">
						<i class="fa fa-instagram" aria-hidden="true"></i>
					</a>
					<a href="http://www.rssboard.org/">
						<i class="fa fa-rss" aria-hidden="true"></i>
					</a>
				</div>


        </div>
    </div>

</body>

</html>

mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}

{% block title %}
     Контакты
{% endblock %}


{% block content %}

<div id="products">


    {% if locations %} {% for location in locations %}
    <div class="product">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>{{ location.city }}</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>{{ location.phone }}</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>{{ location.email }}</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>{{ location.address }}</p>
            </div>
        </div>
    </div>
    {% endfor %}

<!--
    <h1 class="h1_new_products">ЗАПОМНИТЕ НАШИ НОМЕРА</h1>
                         -->

                        {% else %} Здесь пока ничего нет {% endif %}
        </div>

{%endblock%}

mainapp/templates/mainapp/inc-menu.html
{% load staticfiles %}

<div id="menu">
	<div id="name_menu">
		<p>МЕНЮ</p>
	</div>
	<ul id="ul_menu">


         <li>
        <a href="{% url 'mainapp:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == '0' %}active{% endif %}">
            ВСЕ ТОВАРЫ
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'mainapp:page' link.pk 1 %}" class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">
                {{ link.name|upper  }}
            </a>
        </li>
    {% endfor %}

<hr>

    {% if user.is_authenticated %}
        <li>
        <a href="{% url 'auth:edit' %}"> {{ user.first_name|default:'Пользователь'|upper}}</a>
        </li>
        {% endif %}
        {% if user.is_superuser %}
        <li> <a href="{% url 'admin:users' %}">АДМИНКА</a> </li>
        {% endif %}
        <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">ВЫЙТИ</a>
        {%  else %}
        <a href="{% url 'auth:login' %}">ВОЙТИ</a>
        </li>
        {% endif %}
        <li>
        <a href="{% url 'contacts:contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                <p> КОНТАКТЫ </p>  </a>
        </li>

        <li>
        <a href="{% url 'basket:view' %}" class="basket">
            <span>
                {% if basket %}
                <p> <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    ({{ basket.0.get_totalquantity }} шт) товаров на {{ basket.0.get_totalcost|floatformat:0 }}
                    <i class="fa fa-rub" aria-hidden="true"></i>


                </p>

                {% endif %}
            </span>
        </a>
        </li>


	</ul>
</div>

<!--{% for item in menu %}-->
		<!--<li>-->
			<!--<a href="{% url item.1 %}">{{item.0|upper}}</a>-->
		<!--</li>-->
	<!--{% endfor %}-->

mainapp/templates/mainapp/product.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}



{% block content %}
<div id="products">
<div class="new_products">
        {% if product %}
<div class="product">
<img src="{{product.image.url}}" alt={{product.name}}>
</div>


<h2>{{product.desc_full}}</h2>

<div class="price"><h2>{{product.price}} <i class="fa fa-rub" aria-hidden="true"></i></h2>  </div>
        <hr>

<button class="btn btn-secondary"><a href="{% url 'basket:add' product.pk %}">Добавить в корзину
    <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
        </button>

        {% else %} Здесь ничего нет {% endif %}
    </div>
</div>
{%endblock%}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}


{% block content %}
<div id="products">


           <div class="title_clearfix">
            <h2>Категория:"{{category.name|title}}"</h2>
            <div class="paginator">

                {% if products.has_previous %}
                    <a href="{% url 'mainapp:page' category.pk products.previous_page_number %}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
                {% endif %}
                {%if products.number%}
                <span class="current">
                страница {{ products.number }} из {{ products.paginator.num_pages }}
                </span>
                {% endif %}
                {% if products.has_next %}
                    <a href="{% url 'mainapp:page' category.pk products.next_page_number %}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                {% endif %}


            </div>
        </div>
 <div class="new_products">
        {% if products %} {% for product in products %}

        <div class="product">
            <a href="{% url 'mainapp:product' product.pk %}">
                <img src="{{product.image.url|default_if_none:'#'}}" alt={{product.name}}/>
                <h2>{{product.desc}}
                    <div class="price"> {{product.price}}
                    <i class="fa fa-rub" aria-hidden="true"></i>
                    </div></h2>

            </a>

        </div>

        {% endfor %}

        {% else %} Здесь пока ничего нет {% endif %}
    </div>
</div>
{%endblock%}